# Generated by Django 5.2.8 on 2025-11-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exhibitor_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('contact_person_name', models.CharField(max_length=255, verbose_name='Contact Person Name')),
                ('designation', models.CharField(max_length=255, verbose_name='Designation')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('product_service', models.CharField(max_length=255, verbose_name='Product/Service')),
                ('company_address', models.TextField(verbose_name='Company Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exhibitor Registration',
                'verbose_name_plural': 'Exhibitor Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Exhibitor',
        ),
    ]
