# Generated by Django 5.2.6 on 2025-11-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exhibitorregistration_delete_exhibitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=255, verbose_name='Visitor Name')),
                ('Last_name', models.CharField(max_length=255, verbose_name='Visitor Last Name')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('industry', models.CharField(max_length=255, verbose_name='Industry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitor Registration',
                'verbose_name_plural': 'Visitor Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
