# Generated by Django 5.2.6 on 2025-11-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vistorregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitorregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vistorregistration',
            name='First_name',
            field=models.CharField(max_length=255, verbose_name='Firts Name'),
        ),
        migrations.AlterField(
            model_name='vistorregistration',
            name='Last_name',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
    ]
