# Generated by Django 5.2.6 on 2025-11-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_event_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='buyers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='event',
            name='exhibitors',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_past',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sectors',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='buyers_count',
            field=models.CharField(default='6000+', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='countries_count',
            field=models.CharField(default='40+', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='exhibitors_count',
            field=models.CharField(default='400+', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sectors_count',
            field=models.CharField(default='16', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='time_schedule',
            field=models.CharField(default='10:00 AM - 7:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
